# Используем официальный golang-образ для сборки
FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o attendance-api ./cmd/main.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/attendance-api .

EXPOSE 8080

CMD ["./attendance-api"] 